 const games = [
    {   
        "title": "Mass Effect 2",
        "release": "Jan 26, 2010",
        "developer": "Bioware",
        "genre": "Action RPG",
        "score": 8.9,
        "platforms": ["PC", "PlayStation 3", "Xbox 360"],
        "price": 19.99,
    },
    {   
        "title": "The Elder Scrolls V: Skyrim",
        "release": "Nov 11, 2011",
        "developer": "Bethesda Game Studios",
        "genre": "First-Person",
        "score": 8.5,
        "platforms": ["PC", "PlayStation 3", "Xbox 360"],
        "price": 19.99,
    },
    {   
        "title": "Baldur's Gate",
        "release": "Sep 34, 2000",
        "developer": "Bioware",
        "genre": "PC-style RPG",
        "score": 9.2,
        "platforms": ["PC"],
        "price": 9.99,
    },
    {   
        "title": "Divinity: Original Sin II",
        "release": "Aug 31, 2018",
        "developer": "Larian Studios",
        "genre": "Western-Style RPG",
        "score": 8.9,
        "platforms": ["PC", "PlayStation 4", "Xbox One"],
        "price": 39.99,
    },
    {   
        "title": "Final Fantasy IX",
        "release": "Nov 13, 2000",
        "developer": "SquareSoft",
        "genre": "Console-style RPG",
        "score": 9.2,
        "platforms": ["PlayStation"],
        "price": 14.99,
    },
    {   
        "title": "Chrono Cross",
        "release": "Aug 15, 2000",
        "developer": "SquareSoft",
        "genre": "Console-style RPG",
        "score": 8.8,
        "platforms": ["Playstation"],
        "price": 9.99,
    },
    {   
        "title": "The Elder Scrolls IV: Oblivion",
        "release": "Mar 20, 2006",
        "developer": "Bethesda Softworks",
        "genre": "First-Person RPG",
        "score": 8.7,
        "platforms": ["PC", "PlayStation 3", "Xbox 360"],
        "price": 14.99,
    },
    {   
        "title": "Divinity: Original Sin",
        "release": "Oct 27, 2015",
        "developer": "Larian Studios",
        "genre": "Action RPG",
        "score": 8.3,
        "platforms": ["PC", "PlayStation 4", "Xbox One"],
        "price": 29.99,
    },
    {   
        "title": "Diablo",
        "release": "Dec 31, 1996",
        "developer": "Blizzard Entertainment",
        "genre": "Action RPG",
        "score": 8.7,
        "platforms": ["PC"],
        "price": 9.99,
    },
    {   
        "title": "Bastion",
        "release": "Aug 30, 2012",
        "developer": "Warner Bros Interactive",
        "genre": "Action RPG",
        "score": 8.1,
        "platforms": ["PC", "PlayStation 4", "Xbox 360", "Xbox One", "Nintendo Switch"],
        "price": 14.99,
    },
    {   
        "title": "Star Wars: Knights of the Old Republic",
        "release": "Jul 17, 2003",
        "developer": "BioWare",
        "genre": "Third-person",
        "score": 9.0,
        "platforms": ["PC"],
        "price": 4.99,
    },
    {   
        "title": "The Witcher 3: Wild Hunt",
        "release": "May 18, 2015",
        "developer": "CD Projekt Red Studio",
        "genre": "Action RPG",
        "score": 9.3,
        "platforms": ["PC", "PlayStation 4", "Xbox One"],
        "price": 29.99,
    },
    {   
        "title": "Fallout 3",
        "release": "Oct 28, 2008",
        "developer": "Bethesda Game Studios",
        "genre": "First-person RPG",
        "score": 8.5,
        "platforms": ["PC", "PlayStation 3"],
        "price": 19.99,
    },
    {   
        "title": "Mass Effect 3",
        "release": "Mar 5, 2012",
        "developer": "BioWare",
        "genre": "Action RPG",
        "score": 5.6,
        "platforms": ["PC", "PlayStation 3", "Xbox 360"],
        "price": 9.99,
    },
    {   
        "title": "World of Warcraft",
        "release": "Nov 23, 2004",
        "developer": "Blizzard Entertainent",
        "genre": "MMORPG",
        "score": 7.4,
        "platforms": ["PC"],
        "price": 19.99,
    },
    {   
        "title": "BloodBorne",
        "release": "Mar 24, 2015",
        "developer": "From Software",
        "genre": "Action RPG",
        "score": 8.9,
        "platforms": ["PlayStation 4"],
        "price": 59.99,
    },
    {   
        "title": "Vagrant Story",
        "release": "May 15, 2000",
        "developer": "SquareSoft",
        "genre": "Japanese-style RPG",
        "score": 9.0,
        "platforms": ["PlayStation"],
        "price": 9.99,
    },
    {   
        "title": "Final Fantasy XII",
        "release": "Oct 31, 2006",
        "developer": "Square Enix",
        "genre": "Console-style RPG",
        "score": 8.0,
        "platforms": ["PlayStation 2"],
        "price": 19.99,
    },
    {   
        "title": "Final Fantasy X",
        "release": "Dec 17, 2001",
        "developer": "SquareSoft",
        "genre": "Console-style RPG",
        "score": 9.0,
        "platforms": ["PlayStation 2"],
        "price": 19.99,
    },
    {   
        "title": "Final Fantasy VII",
        "release": "Sep 3, 1997",
        "developer": "SquareSoft",
        "genre": "Console-style RPG",
        "score": 9.2,
        "platforms": ["PC", "PlayStation"],
        "price": 14.99,
    },
    {   
        "title": "Chrono Trigger",
        "release": "Nov 25, 2008",
        "developer": "TOSE",
        "genre": "Japanese-style RPG",
        "score": 9.2,
        "platforms": ["Super Nintendo","PlayStation"],
        "price": 9.99,
    },
    {   
        "title": "Xenoblade Chronicles",
        "release": "Apr 6, 2012",
        "developer": "Monolith Soft",
        "genre": "Action RPG",
        "score": 9.2,
        "platforms": ["Wii"],
        "price": 29.99,
    },
    {   
        "title": "Dark Souls II",
        "release": "Mar 11, 2014",
        "developer": "From Software",
        "genre": "Action RPG",
        "score": 7.9,
        "platforms": ["PC", "PlayStation 3", "Xbox 360"],
        "price": 19.99,
    },
    {   
        "title": "Baldur's Gate II: Shadows_of_Amn",
        "release": "Sep 21, 2000",
        "developer": "BioWare",
        "genre": "PC-style RPG",
        "score": 8.8,
        "platforms": ["PC"],
        "price": 9.99,
    },
    {   
        "title": "Monster Hunter: World",
        "release": "Jan 26, 2018",
        "developer": "Capcom",
        "genre": "Action RPG",
        "score": 7.7,
        "platforms": ["PC", "PlayStation 4", "Xbox One"],
        "price": 59.99,
    },
    {   
        "title": "Guild Wars 2",
        "release": "Aug 28, 2012",
        "developer": "ArenaNet",
        "genre": "MMORPG",
        "score": 8.1,
        "platforms": ["PC"],
        "price": 9.99,
    },
    {   
        "title": "Final Fantasy VIII",
        "release": "Sep 7, 1999",
        "developer": "SquareSoft",
        "genre": "Console-style RPG",
        "score": 9.0,
        "platforms": ["PC", "PlayStation"],
        "price": 9.99,
    },
    {   
        "title": "Dark Souls III",
        "release": "Apr 11, 2016",
        "developer": "From Software",
        "genre": "Action RPG",
        "score": 8.5,
        "platforms": ["PC", "PlayStation 4", "Xbox One"],
        "price": 29.99,
    },
    {   
        "title": "Demon Souls",
        "release": "Oct 6, 2009",
        "developer": "From Software",
        "genre": "Action RPG",
        "score": 8.9,
        "platforms": ["PlayStation 3"],
        "price": 14.99,
    },
    {   
        "title": "Pillars of Eternity",
        "release": "Mar 26, 2015",
        "developer": "Obsidian Entertainment",
        "genre": "Third-person RPG",
        "score": 8.3,
        "platforms": ["PC"],
        "price": 19.99,
    },
    {   
        "title": "Castlevania: Symphony of the Night",
        "release": "Mar 21, 2007",
        "developer": "Digital Eclipse",
        "genre": "Action RPG",
        "score": 8.7,
        "platforms": ["PlayStation", "Xbox 360"],
        "price": 9.99,
    },
    {   
        "title": "The Elder Scrolls III: Morrowind",
        "release": "May 1, 2002",
        "developer": "Bethesda Softworks",
        "genre": "First-person RPG",
        "score": 8.9,
        "platforms": ["PC", "Xbox 360"],
        "price": 4.99,
    },
    {   
        "title": "Fable II",
        "release": "Oct 21, 2008",
        "developer": "Lionhead Studios",
        "genre": "Action RPG",
        "score": 6.6,
        "platforms": ["Xbox 360"],
        "price": 4.99,
    }
]


module.exports = games;